# -*- coding: utf-8 -*-
"""AIA5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fAKfiEuX25F5voZKcTI9CXH5h2SpTsSh
"""

!apt install swi-prolog

!pip install pyswip

import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from pyswip import Prolog

def output(var):
    if var == "MachineLearning&ArtificialIntelligence": 
      print('AI,ML,DMG,SML,GradAlgo')
    if var == "GraphicDesigning": 
      print('ComputerArchitecture,ComputerGraphics,GradAlgo')
    if var == "InformationSecurity": 
      print('EthicalHacking,ProgramAnalysis,GradAlgo')
    if var == "Networking": 
      print('MobileComputing,EmbeddedSystems,Mobileandcellularnetworksecurity,GradAlgo')
    else:
        print("We recommend you to explore more about your interests and come back again.")

ps = PorterStemmer()

f = open("/content/nlinterface.txt", 'w')

inplist = []
inp1 = input('Enter branch: ')
tok1 = word_tokenize(inp1)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "cse" in inplist:
  f.write("branch(cse).\n")

inplist = []
inp2 = input('Enter CGPA: ')
tok1 = word_tokenize(inp2)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "9" in inplist:
  f.write("cgpa(9.0).\n")
elif  "8" in inplist:
  f.write("cgpa(8.0).\n")
elif  "7" in inplist:
  f.write("cgpa(7.0).\n")
elif  "6" in inplist:
  f.write("cgpa(6.0).\n")
elif  "6.5" in inplist:
  f.write("cgpa(6.5).\n")
else:
  f.write("cgpa(7.5).\n")

inplist = []
inp3 = input('Do you have a strong grasp of mathematics and statistics?')
tok1 = word_tokenize(inp3)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("maths(y).\n")

inplist = []
inp4 = input("Do you like programming? ")
tok1 = word_tokenize(inp4)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("programming(y).\n")

inplist = []
inp5 = input('Are you considering a career in ML?')
tok1 = word_tokenize(inp5)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("machine_learning(y).\n")

inplist = []
inp6 = input('Are you considering a career in AI?')
tok1 = word_tokenize(inp6)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("artificial_intelligence(y).\n")

inplist = []
inp7 = input('Are you considering a career in Data Mining?')
tok1 = word_tokenize(inp7)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("data_mining(y).\n")

inplist = []
inp8 = input('Are you considering a career in Networking?')
tok1 = word_tokenize(inp8)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("networking(y).\n")

inplist = []
inp9 = input('Are you considering a career in Graphic Designing?')
tok1 = word_tokenize(inp9)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("graphic_designing(y).\n")

inplist = []
inp10 = input('Are you considering a career in Information Security?')
tok1 = word_tokenize(inp10)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("information_security(y).\n")

inplist = []
inp11 = input('Are you considering to study further?')
tok1 = word_tokenize(inp)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "y" in inplist:
  f.write("higher_studies(y).\n")

f.close()

swipl = Prolog()
swipl.consult("/content/electiveAdvisory.pl")
electives_suggested = list(swipl.query("generate_electives(Electives)"))
for i in range(len(electives_suggested)):
    var = electives_suggested[i]['Electives'].decode('utf-8')
    output(var)

